// <auto-generated />
using System;
using FifApi.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FifApi.Migrations
{
    [DbContext(typeof(FootDBContext))]
    [Migration("20240312150455_FifaBDD")]
    partial class FifaBDD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FifApi.Models.EntityFramework.Joueur", b =>
                {
                    b.Property<int>("PosteId")
                        .HasColumnType("int")
                        .HasColumnName("posteId");

                    b.Property<DateTime>("DateDecesJoueur")
                        .HasColumnType("Date")
                        .HasColumnName("dateDecesJoueur");

                    b.Property<DateTime>("DateNaissanceJoueur")
                        .HasColumnType("Date")
                        .HasColumnName("dateNaissanceJoueur");

                    b.Property<DateTime>("DebutCarriereJoueur")
                        .HasColumnType("Date")
                        .HasColumnName("debutCarriereJoueur");

                    b.Property<string>("DescriptionJoueur")
                        .IsRequired()
                        .HasColumnType("Varchar(1000)")
                        .HasColumnName("descriptionJoueur");

                    b.Property<DateTime>("FinCarriereJoueur")
                        .HasColumnType("Date")
                        .HasColumnName("finCarriereJoueur");

                    b.Property<int>("IdJoueur")
                        .HasColumnType("int")
                        .HasColumnName("idJoueur");

                    b.Property<string>("NomJoueur")
                        .IsRequired()
                        .HasColumnType("Varchar(150)")
                        .HasColumnName("nomJoueur");

                    b.Property<string>("PrenomJoueur")
                        .IsRequired()
                        .HasColumnType("Varchar(150)")
                        .HasColumnName("prenomJoueur");

                    b.Property<string>("SexeJoueur")
                        .IsRequired()
                        .HasColumnType("Char(1)")
                        .HasColumnName("sexeJoueur");

                    b.HasKey("PosteId")
                        .HasName("pk_joueur");

                    b.ToTable("joueur");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.JoueurMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("matchId");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int")
                        .HasColumnName("joueurId");

                    b.Property<int>("NbButs")
                        .HasColumnType("int")
                        .HasColumnName("nbButs");

                    b.HasKey("MatchId", "JoueurId")
                        .HasName("pk_joueurMatch");

                    b.HasIndex("JoueurId");

                    b.ToTable("joueurMatch");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMarque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("NomMarque")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nomMarque");

                    b.HasKey("IdMarque");

                    b.ToTable("marque");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Match", b =>
                {
                    b.Property<int>("IdMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMatch");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatch"));

                    b.Property<DateTime>("DateMatch")
                        .HasColumnType("Date")
                        .HasColumnName("dateMatch");

                    b.Property<string>("NomMatch")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("nomMatch");

                    b.Property<int>("ScoreEquipeDomicile")
                        .HasColumnType("int")
                        .HasColumnName("scoreEquipeDomicile");

                    b.Property<int>("ScoreEquipeExterieure")
                        .HasColumnType("int")
                        .HasColumnName("scoreEquipeExterieure");

                    b.HasKey("IdMatch");

                    b.ToTable("match");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Poste", b =>
                {
                    b.Property<int>("Idposte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idposte");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idposte"));

                    b.Property<string>("DescriptionPoste")
                        .IsRequired()
                        .HasColumnType("Varchar(300)")
                        .HasColumnName("descriptionPoste");

                    b.Property<string>("NomPoste")
                        .IsRequired()
                        .HasColumnType("Varchar(150)")
                        .HasColumnName("nomPoste");

                    b.HasKey("Idposte");

                    b.ToTable("poste");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Produit", b =>
                {
                    b.Property<int>("MarqueId")
                        .HasColumnType("int");

                    b.Property<string>("CaracteristiquesProduit")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("caracteristiquesproduit");

                    b.Property<string>("DescriptionProduit")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descriptionproduit");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int")
                        .HasColumnName("idproduit");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nomproduit");

                    b.HasKey("MarqueId")
                        .HasName("pk_produit");

                    b.ToTable("produit");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Joueur", b =>
                {
                    b.HasOne("FifApi.Models.EntityFramework.Poste", "PostePourJoueur")
                        .WithMany("JoueurPoste")
                        .HasForeignKey("PosteId")
                        .IsRequired()
                        .HasConstraintName("fk_joueur_poste");

                    b.Navigation("PostePourJoueur");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.JoueurMatch", b =>
                {
                    b.HasOne("FifApi.Models.EntityFramework.Joueur", "JoueurDansMatch")
                        .WithMany("JouabiliteMatch")
                        .HasForeignKey("JoueurId")
                        .IsRequired()
                        .HasConstraintName("fk_joueurMatch_joueur");

                    b.HasOne("FifApi.Models.EntityFramework.Match", "MatchPourJoueur")
                        .WithMany("JouabiliteMatch")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("fk_joueurMatch_match");

                    b.Navigation("JoueurDansMatch");

                    b.Navigation("MatchPourJoueur");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Produit", b =>
                {
                    b.HasOne("FifApi.Models.EntityFramework.Marque", "MarqueduProduit")
                        .WithMany("ProduitMarque")
                        .HasForeignKey("MarqueId")
                        .IsRequired()
                        .HasConstraintName("fk_produit_marque");

                    b.Navigation("MarqueduProduit");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Joueur", b =>
                {
                    b.Navigation("JouabiliteMatch");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Marque", b =>
                {
                    b.Navigation("ProduitMarque");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Match", b =>
                {
                    b.Navigation("JouabiliteMatch");
                });

            modelBuilder.Entity("FifApi.Models.EntityFramework.Poste", b =>
                {
                    b.Navigation("JoueurPoste");
                });
#pragma warning restore 612, 618
        }
    }
}
